#define u_int16 unsigned short int
#define u_char8 unsigned char
#define u_long_int unsigned long int
#define u_long_int64 unsigned long long int
#define White 15
#define Light_Brown 14
#define Light_Magenta 13
#define Light_Red 12
#define Light_Cyan 11
#define Light_Green 10
#define Light_Blue 9
#define Dark_Grey 8
#define Light_Grey 7
#define Brown 6
#define Magenta 5
#define Red 4
#define Cyan 3
#define Green 2
#define Blue 1
#define Black 0